###############################################################################
#
#    Service Config section
#
###############################################################################
server:
  port: 3000
  mode: debug  # debug;release
  upload_dir: /home/eric/docker-v/fileserver/html/file/
  upload_url: http://localhost:5000/file/